# -*- coding: utf-8 -*-
{
    'name': 'AIVIO Maintenance Service',
    'version': '19.0.1.0.0',
    'category': 'AIVIO',
    'summary': 'Community maintenance tickets, teams, worksheets, images, and resident ratings.',
    'description': 'Custom Helpdesk-like maintenance app for Odoo 19 Community without Enterprise Helpdesk dependency.',
    'author': 'AIVIO',
    'maintainer': 'AIVIO',
    'website': 'https://www.aivio.ai',
    'license': 'LGPL-3',
    'depends': ['aivio_mobile_core', 'aivio_residence', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/aivio_maintenance_rules.xml',
        'data/maintenance_sequences.xml',
        'data/maintenance_stage_data.xml',
        'views/res_users_views.xml',
        'views/maintenance_stage_views.xml',
        'views/maintenance_team_views.xml',
        'views/maintenance_category_views.xml',
        'views/maintenance_ticket_views.xml',
        'views/maintenance_worksheet_views.xml',
        'views/ticket_rating_views.xml',
        'views/maintenance_menus.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': False,
    'auto_install': False,
}
