# -*- coding: utf-8 -*-
{
    'name': 'AIVIO Security Gate',
    'version': '19.0.1.0.0',
    'category': 'AIVIO',
    'summary': 'Security gates, visitor QR passes, check-in/check-out logs, incidents, and blacklist.',
    'description': 'Community-ready security and gate management for AIVIO mobile guard app.',
    'author': 'AIVIO',
    'maintainer': 'AIVIO',
    'website': 'https://www.aivio.ai',
    'license': 'LGPL-3',
    'depends': ['aivio_mobile_core', 'aivio_residence', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/aivio_security_gate_rules.xml',
        'data/security_sequences.xml',
        'views/res_users_views.xml',
        'views/security_gate_views.xml',
        'views/guard_shift_views.xml',
        'views/visitor_visit_views.xml',
        'views/access_log_views.xml',
        'views/security_incident_views.xml',
        'views/blacklist_views.xml',
        'views/security_menus.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': False,
    'auto_install': False,
}
