# -*- coding: utf-8 -*-
{
    'name': 'AIVIO Residence Community',
    'version': '19.0.1.0.0',
    'category': 'AIVIO',
    'summary': 'Residential community residents, family members, vehicles, and mobile banners.',
    'description': 'Extends AIVIO Real Estate with resident profiles, portal user unit links, family, cars, and resident app content.',
    'author': 'AIVIO',
    'maintainer': 'AIVIO',
    'website': 'https://www.aivio.ai',
    'license': 'LGPL-3',
    'depends': ['aivio_real_estate', 'aivio_mobile_core', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/aivio_residence_rules.xml',
        'data/residence_sequences.xml',
        'views/res_users_views.xml',
        'views/res_partner_views.xml',
        'views/resident_profile_views.xml',
        'views/family_member_views.xml',
        'views/vehicle_views.xml',
        'views/ads_banner_views.xml',
        'views/residence_menus.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': False,
    'auto_install': False,
}
